### ISSUE TITLE
All data appears empty vieweing a polars dataframe  in PyCharm Communty Edition 2024.2.1

### ISSUE THREAD

**Issue by comintel** [rendner/py-plugin-dataframe-viewer#12]
I use your extension constantly to view Polars dataframes while debugging.
Everything worked fine until I upgraded PyCharm to PyCharm Community Edition 2024.2.1 today.

After I did so, viewing any polars dataframe at all just showed empty data.  The rows were all there, but there were no numbers or other values shown, just blanks.

I have installed an earlier version now and all is back to normal.

This is on Windows 11.

Thanks.

**Comment by rendner** [comment]
Thank you for the information.

It seems that the plugin does not work with PyCharm due to a bug in PyCharm 2024.2.1. I am currently not aware of any workaround except downgrading PyCharm.

I have already reported this problem: https://youtrack.jetbrains.com/issue/PY-75581
If you have an YouTrack account, you can vote on the issue to increase its importance.

**Comment by comintel** [comment]
Thank you so much for identifying the problem so quickly!
I have already downgraded, so I am fine for now.
I have up-voted the bug.

**Comment by rendner** [comment]
@comintel I found a temporary workaround for the plugin: [WORKAROUND_PYCHARM_2024.2.1_TO_2025.1.md](https://github.com/rendner/py-plugin-dataframe-viewer/blob/main/docs/WORKAROUND_PYCHARM_2024.2.1_TO_2025.1.md)

**Comment by comintel** [comment]
I can confirm it is working perfectly now after re-upgrading and applying your workaround.

It is great to be back debugging Polars code with the latest PyCharm release!

(Personally I do not understand how anyone can be doing Polars development efficiently  without the only known full capability viewer, namely yours).

Thanks!
